--- #YAML:1.0
name:                BS-HTTPD
version:             0.01
abstract:            A simple lightweight event based web (application) server
license:             ~
author:              
    - Robin Redeker <elmex@ta-sa.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    BS::Event:                     0
    HTTP::Date:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
